[pytest]
addopts = --cache-clear
filterwarnings =
    ignore:Unverified HTTPS request
    ignore::DeprecationWarning
console_output_style = progress
bdd_features_base_dir = features/
markers =
    low: Low priority test
    medium: Medium priority test
    high: High priority test